version: '3'

services:
  clickcount:
    image: horgix/click-count-doc:latest
    networks:
      - traefik-network
    labels:
      traefik.enable:         "true"
      traefik.port:           "80"
      traefik.backend:        "clickcount"
      traefik.frontend.rule:  "Host:clickcount.test.deploy.coffee"

networks:
  traefik-network:
    external: True
