version: '3'

services:
  blog:
    image: horgix/blog:latest
    networks:
      - traefik-network
    labels:
      traefik.enable:       "true"
      traefik.port:         "80"
      traefik.backend:      "blog"
      traefik.frontend.rule: "Host:blog.horgix.fr"

networks:
  traefik-network:
    external: True
