version: '3'

services:
  resume:
    image: horgix/resume:latest
    networks:
      - traefik-network
    labels:
      traefik.enable:         "true"
      traefik.port:           "80"
      traefik.backend:        "resume"
      traefik.frontend.rule:  "Host:resume.horgix.fr,cv.horgix.fr,horgix.fr"

networks:
  traefik-network:
    external: True
