version: '3'

services:
  saltmaster:
    container_name: saltmaster
    image: horgix/salt-master:2017.7.0
    ports:
      - "4505:4505"
      - "4506:4506"
    volumes:
      - /srv/docker_volumes/salt/etc/salt:/etc/salt
      - /srv/docker_volumes/salt/var/cache/salt:/var/cache/salt
      - /srv/docker_volumes/salt/var/logs/salt:/var/logs/salt
      - /srv/docker_volumes/salt/srv/salt:/srv/salt
      - /srv/docker_volumes/salt/srv/pillar:/srv/pillar
      - /srv/docker_volumes/salt/var/run/salt:/var/run/salt
